language: php
php:
  - 5.4

install: 
  - composer install

services:
  - redis-server

before_script:
  - mysql -e 'create database TourATourTest;'
  - mysql TourATourTest < Database/structure.sql

script: 
  - phpunit Tests/AllTests.php